export const TYPES = {
    SET_LOGIN: 'TYPE.SET_LOGIN',
    CHOOSE_SIDEBAR: 'CHOOSE_SIDEBAR',
    ALL_CARS: 'ALL_CARS',
    NAME_CAR: 'NAME_CAR',
    IS_SUBMIT: 'IS_SUBMIT',
    IS_LOADING: 'IS_LOADING',
  };